version: "3.8"
services:
  app:
    #build: .
    image: 'aetherprior/sud:apr'
    command: ["python","app.py","--docker"]
    ports:
      - "5000:5000"
    volumes:
      - ../data-webapp:/data
    deploy:
      resources:
        limits:
          memory: 16G